name: 'Diambars'
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  create_diambars:
    runs-on: ubuntu-latest
    name: A job to create Diambars
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        env:
          TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
      - name: Diambars action step
        uses: ./.github/actions/diambars # Uses an action in the root directory
      - name: Commit the new README.MD file
        run: |-
          git diff
          git config --global user.email "genova@dofbi.com"
          git config --global user.name "Mamadou Diagne"
          git diff --quiet || (git add README.md && git commit -m "Update the README.md")
          git push